In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
df=pd.read_excel(r'D:\Genai_agenticAI\data.xlsx')
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [4]:
df.shape

(195, 5)

In [5]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [6]:
len(df.columns)

5

In [7]:
df.isnull

<bound method DataFrame.isnull of               CountryName CountryCode  BirthRate  InternetUsers  \
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

             IncomeGroup
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]>

In [8]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [9]:
df.isna().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB
None

In [11]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [12]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [13]:
df.tail(20)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
175,Tunisia,TUN,19.800,43.80,Upper middle income
176,Turkey,TUR,16.836,46.25,Upper middle income
177,Tanzania,TZA,39.518,4.40,Low income
178,Uganda,UGA,43.474,16.20,Low income
179,Ukraine,UKR,11.100,41.00,Lower middle income
180,Uruguay,URY,14.374,57.69,High income
181,United States,USA,12.500,84.20,High income
182,Uzbekistan,UZB,22.500,38.20,Lower middle income
183,St. Vincent and the Grenadines,VCT,16.306,52.00,Upper middle income
184,"Venezuela, RB",VEN,19.842,54.90,High income
185,Virgin Islands (U.S.),VIR,10.700,45.30,High income
186,Vietnam,VNM,15.537,43.90,Lower middle income
187,Vanuatu,VUT,26.739,11.30,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.60,Lower middle income
189,Samoa,WSM,26.172,15.30,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.00,Lower middle income
191,South Africa,ZAF,20.850,46.50,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.20,Low income
193,Zambia,ZMB,40.471,15.40,Lower middle income
194,Zimbabwe,ZWE,35.715,18.50,Low income

In [14]:
df[:10]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [15]:
df[10:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.7000,Upper middle income
11,Burundi,BDI,44.151,1.3000,Low income
12,Belgium,BEL,11.200,82.1702,High income
13,Benin,BEN,36.440,4.9000,Low income
14,Burkina Faso,BFA,40.551,9.1000,Low income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0000,Lower middle income
191,South Africa,ZAF,20.850,46.5000,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2000,Low income
193,Zambia,ZMB,40.471,15.4000,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5000,Low income

In [16]:
df[10:20]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income

In [17]:
df[::10]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

In [18]:
df.columns[3]

'InternetUsers'

In [19]:
df.head(10)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [20]:
df.tail(12)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
183,St. Vincent and the Grenadines,VCT,16.306,52.0,Upper middle income
184,"Venezuela, RB",VEN,19.842,54.9,High income
185,Virgin Islands (U.S.),VIR,10.700,45.3,High income
186,Vietnam,VNM,15.537,43.9,Lower middle income
187,Vanuatu,VUT,26.739,11.3,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.6,Lower middle income
189,Samoa,WSM,26.172,15.3,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [21]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [22]:
df.IncomeGroup.unique()

array(['High income', 'Low income', 'Upper middle income',
       'Lower middle income'], dtype=object)

In [23]:
#df.mean('Low income')

In [25]:
len(df)

195

In [26]:
df.shape

(195, 5)

In [27]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [28]:
len(df.columns)

5

In [29]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [31]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [32]:
df.isna().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [34]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [35]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [36]:
df[:10]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [37]:
df[::-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

In [38]:
df[10:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.7000,Upper middle income
11,Burundi,BDI,44.151,1.3000,Low income
12,Belgium,BEL,11.200,82.1702,High income
13,Benin,BEN,36.440,4.9000,Low income
14,Burkina Faso,BFA,40.551,9.1000,Low income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0000,Lower middle income
191,South Africa,ZAF,20.850,46.5000,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2000,Low income
193,Zambia,ZMB,40.471,15.4000,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5000,Low income

In [39]:
df[10:20]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income

In [40]:
df[::10]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

In [41]:
df.dtypes

CountryName       object
CountryCode       object
BirthRate        float64
InternetUsers    float64
IncomeGroup       object
dtype: object

In [42]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [44]:
df[['CountryName','InternetUsers']]

              CountryName  InternetUsers
0                   Aruba           78.9
1             Afghanistan            5.9
2                  Angola           19.1
3                 Albania           57.2
4    United Arab Emirates           88.0
..                    ...            ...
190           Yemen, Rep.           20.0
191          South Africa           46.5
192      Congo, Dem. Rep.            2.2
193                Zambia           15.4
194              Zimbabwe           18.5

[195 rows x 2 columns]

In [46]:
df[:1]

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [47]:
df[['CountryName','CountryCode','BirthRate']]

              CountryName CountryCode  BirthRate
0                   Aruba         ABW     10.244
1             Afghanistan         AFG     35.253
2                  Angola         AGO     45.985
3                 Albania         ALB     12.877
4    United Arab Emirates         ARE     11.044
..                    ...         ...        ...
190           Yemen, Rep.         YEM     32.947
191          South Africa         ZAF     20.850
192      Congo, Dem. Rep.         COD     42.394
193                Zambia         ZMB     40.471
194              Zimbabwe         ZWE     35.715

[195 rows x 3 columns]

In [ ]:
#split the dataset into numerical dataframes & cat data frmaes

In [48]:
df_num=df[['BirthRate','InternetUsers']]
df_cat=df[['CountryName','CountryCode','IncomeGroup']]

In [49]:
df_num.head(2)

   BirthRate  InternetUsers
0     10.244           78.9
1     35.253            5.9

In [50]:
df_cat.head(2)

   CountryName CountryCode  IncomeGroup
0        Aruba         ABW  High income
1  Afghanistan         AFG   Low income

In [51]:
print(df_num.columns)
print(df_cat.columns)

Index(['BirthRate', 'InternetUsers'], dtype='object')
Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')

In [52]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [53]:
df_num.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [54]:
df_cat.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [55]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [58]:
df.columns=['a','b','c','d','e']

In [59]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [61]:
df.columns=['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup']

In [62]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [63]:
df.BirthRate*df.InternetUsers

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

In [64]:
df['sum']=df.BirthRate*df.InternetUsers

In [65]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup       sum
0        Aruba         ABW     10.244           78.9  High income  808.2516
1  Afghanistan         AFG     35.253            5.9   Low income  207.9927

In [67]:
id(df)

1756425253424

In [68]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,sum
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720
...,...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income,658.9400
191,South Africa,ZAF,20.850,46.5,Upper middle income,969.5250
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534
194,Zimbabwe,ZWE,35.715,18.5,Low income,660.7275

In [69]:
df.drop('sum',axis=1)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [ ]:
#filters in dataframe

In [70]:
df.InternetUsers<2

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Name: InternetUsers, Length: 195, dtype: bool

In [73]:
df[df.InternetUsers<2]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,sum
11,Burundi,BDI,44.151,1.3,Low income,57.3963
52,Eritrea,ERI,34.800,0.9,Low income,31.3200
55,Ethiopia,ETH,32.925,1.9,Low income,62.5575
64,Guinea,GIN,37.337,1.6,Low income,59.7392
117,Myanmar,MMR,18.119,1.6,Lower middle income,28.9904
127,Niger,NER,49.661,1.7,Low income,84.4237
154,Sierra Leone,SLE,36.729,1.7,Low income,62.4393
156,Somalia,SOM,43.891,1.5,Low income,65.8365
172,Timor-Leste,TLS,35.755,1.1,Lower middle income,39.3305

In [74]:
len(df[df.InternetUsers<2])

9

In [78]:
df[df.BirthRate>40]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,sum
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
11,Burundi,BDI,44.151,1.3,Low income,57.3963
14,Burkina Faso,BFA,40.551,9.1,Low income,369.0141
65,"Gambia, The",GMB,42.525,14.0,Low income,595.3500
115,Mali,MLI,44.138,3.5,Low income,154.4830
127,Niger,NER,49.661,1.7,Low income,84.4237
128,Nigeria,NGA,40.045,38.0,Lower middle income,1521.7100
156,Somalia,SOM,43.891,1.5,Low income,65.8365
167,Chad,TCD,45.745,2.3,Low income,105.2135
178,Uganda,UGA,43.474,16.2,Low income,704.2788
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534

In [81]:
len(df[df.BirthRate>40])

12

In [85]:
df[(df.InternetUsers<3) & (df.BirthRate>40)]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,sum
11,Burundi,BDI,44.151,1.3,Low income,57.3963
127,Niger,NER,49.661,1.7,Low income,84.4237
156,Somalia,SOM,43.891,1.5,Low income,65.8365
167,Chad,TCD,45.745,2.3,Low income,105.2135
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668

In [86]:
df[df.IncomeGroup=='Low income']

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,sum
1,Afghanistan,AFG,35.253,5.90,Low income,207.99270
11,Burundi,BDI,44.151,1.30,Low income,57.39630
13,Benin,BEN,36.440,4.90,Low income,178.55600
14,Burkina Faso,BFA,40.551,9.10,Low income,369.01410
29,Central African Republic,CAF,34.076,3.50,Low income,119.26600
38,Comoros,COM,34.326,6.50,Low income,223.11900
52,Eritrea,ERI,34.800,0.90,Low income,31.32000
55,Ethiopia,ETH,32.925,1.90,Low income,62.55750
64,Guinea,GIN,37.337,1.60,Low income,59.73920
65,"Gambia, The",GMB,42.525,14.00,Low income,595.35000
66,Guinea-Bissau,GNB,37.503,3.10,Low income,116.25930
77,Haiti,HTI,25.345,10.60,Low income,268.65700
93,Cambodia,KHM,24.462,6.80,Low income,166.34160
99,Liberia,LBR,35.521,3.20,Low income,113.66720
111,Madagascar,MDG,34.686,3.00,Low income,104.05800
115,Mali,MLI,44.138,3.50,Low income,154.48300
120,Mozambique,MOZ,39.705,5.40,Low income,214.40700
123,Malawi,MWI,39.459,5.05,Low income,199.26795
127,Niger,NER,49.661,1.70,Low income,84.42370
132,Nepal,NPL,20.923,13.30,Low income,278.27590
148,Rwanda,RWA,32.689,9.00,Low income,294.20100
154,Sierra Leone,SLE,36.729,1.70,Low income,62.43930
156,Somalia,SOM,43.891,1.50,Low income,65.83650
158,South Sudan,SSD,37.126,14.10,Low income,523.47660
167,Chad,TCD,45.745,2.30,Low income,105.21350
168,Togo,TGO,36.080,4.50,Low income,162.36000
177,Tanzania,TZA,39.518,4.40,Low income,173.87920
178,Uganda,UGA,43.474,16.20,Low income,704.27880
192,"Congo, Dem. Rep.",COD,42.394,2.20,Low income,93.26680
194,Zimbabwe,ZWE,35.715,18.50,Low income,660.72750

In [87]:
df[df.IncomeGroup=='High income']

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,sum
0,Aruba,ABW,10.244,78.90,High income,808.25160
4,United Arab Emirates,ARE,11.044,88.00,High income,971.87200
5,Argentina,ARG,17.716,59.90,High income,1061.18840
7,Antigua and Barbuda,ATG,16.447,63.40,High income,1042.73980
8,Australia,AUS,13.200,83.00,High income,1095.60000
...,...,...,...,...,...,...
174,Trinidad and Tobago,TTO,14.590,63.80,High income,930.84200
180,Uruguay,URY,14.374,57.69,High income,829.23606
181,United States,USA,12.500,84.20,High income,1052.50000
184,"Venezuela, RB",VEN,19.842,54.90,High income,1089.32580
185,Virgin Islands (U.S.),VIR,10.700,45.30,High income,484.71000

In [24]:
import matplotlib.pyplot as plt #visualization
import seaborn as sns #statistical visualization(distribution plto,)

%matplotlib inline #Keep the graph proper shape
plt.rcParams['figure.figsize']=6,2 # height and width of the graph

import warnings #ignore the warning message which cause by system / os updation
warnings.filterwarnings('ignore')

UsageError: unrecognized arguments: #Keep the graph proper shape

In [ ]:
vis1=sns.distplot(df['InternetUsers']) # Univariet

In [ ]:
vis1=sns.displot(df['InternetUsers']) #byvariet

In [ ]:
vis2=sns.distplot(df['InternetUsers'],bins=15)

In [ ]:
vis3=sns.boxplot(data=df,x='IncomeGroup',y='BirthRate')

In [ ]:
vis4=sns.lmplot(data=df,x='InternetUsers',y='BirthRate')

In [ ]:
vis5=sns.lmplot(data=df,x='InternetUsers',y='BirthRate',fit_reg=False)

In [ ]:
vis5=sns.lmplot(data=df,x='InternetUsers',y='BirthRate',fit_reg=True,hue='IncomeGroup')